=encoding utf8

=head1 NAME

mkdcimg - generate MxN convolution and neighborhood generation actors

=head1 SYNOPSIS

mkconv [-name name] [-o file] -dim d -mode (shifted|centered|neigh) -h nr -w nc"

=head1 DESCRIPTION

This program can be used to generate the description in CAPH of MxN convolution and neighborhood generation 
actors. 

=head1 ARGUMENTS

=over

=item -w nc

kernel / neighborhood width (number of columns)


=back

=head1 OPTIONS

=over

=item -o file

write result in file I<file> (default is to write on I<stdout>)

=item -name name

name of the generated actor  (default is I<(conv|cconv|neigh)<dim><h><w>a>)

=item -mode m

kind of actor generated (I<m=shifted> : shifted convolution, I<m=centered> : centered convolution, I<m=neigh> : neighborhood generator) (default: shifted convolution)

=item -dim d

input signal dimension (1 for 1D signals, 2 for 2D images) (default: 1)

=item -h nr

kernel / neighborhood height (number of rows) when I<dim>=2

=back

=head1 EXAMPLES

The following command 

mkconv -dim 1 -mode shifted -w 3

generates (on stdout) the description of an actor I<conv113> computing the shifted I<1x3> convolution of 1D signals (I<i.e.> lists)

The following command

mkconv -o myconv.cph -name conv55 -dim 2 -mode centered -h 5 -w 5 

generates, in file I<myconv.cph>, the description of an actor I<conv55> computing the centered I<5x3> convolution operating on images

=head1 EXIT STATUS

The program returns a zero exist status if it succeeds and a non zero value in case of failure. In
the latter case, an error message is printed to stderr.

=head1 AUTHOR

Jocelyn SE<eacute>rot (jocelyn.serot@univ-bpclermont.fr)

=head1 CAVEAT

The generated convolution actors (shifted or centered) only operate on size and sign generic
integers but the sign and size of the inputs, kernel coefficients and outputs must be the same. It
is not passible, for example, to take a (structured) stream a signed 8-bit integers, convoluate it with a kernel
made of unsigned 4-bit integers and produce a stream of 12-bit signed integers.

Some predefined versions of the actors which can be generated by this program can be found in the 
CAPH library, in files I<convol.cph> and I<neigh.cph>. A detailed description of the convolution and 
neighborhood generation operations is given in these files.

This program appeared in version 2.7.2 of the CAPH distribution.


=head1 SEE ALSO

L<pgm2txt(1)>, L<txt2pgm(1)>, L<txt2bin(1), L<bin2txt>>
