#!/bin/bash

quartus_lib=$CAPH/contrib/lib/quartus
topname=main_net

while : ; do
  case "$1" in
    "") break;;
    -top|--top)
        top=$2; shift;;
    -help|--help)
        cat <<EOF
Usage: mk_quartus_proj [options] target_dir
Options:
  --top kind         toplevel entity [default: main_net]
  --help             print this message
To build a Quartus-ready project 
1. cd <source dir>
2. caphmake
3. make vhdl.makefile
4. make vhdl.code
5. cd vhdl
6. mk_quartus_proj -top <name> <target_dir>
EOF
	exit 0;;
    *) target_dir=$1;;
  esac
  shift
done

qip_name=$top.qip

if [ ! -d $target_dir ]; then
  echo "Creating dir $target_dir"
  mkdir $target_dir
fi

sed -e "s/_MODULE_NAME_/$top/g" $quartus_lib/qsf_templ.qsf > $target_dir/$top.qsf
sed -e "s/_MODULE_NAME_/$top/g" $quartus_lib/qpf_templ.qpf > $target_dir/$top.qpf
cp $quartus_lib/sdc_templ.sdc $target_dir/$top.sdc
cp ./$qip_name $target_dir/$top.qip
sed -e "s/_MODULE_NAME_/$top/g" $quartus_lib/qip_templ.qip >> $target_dir/$top.qip
for f in *.vhd; do
echo "Copying $f to $target_dir"
cp $f $target_dir
done
